#######
# Compiled from data/custom_loot/functions/management.mcscript
# to .//data/custom_loot/functions/deactivate.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard players set #on cl_health 0
execute store result entity @s Health float 1 run scoreboard players get @s cl_health_old
tag @s remove cl_init