#######
# Compiled from data/custom_loot/functions/death.mcscript
# to .//data/custom_loot/functions/death.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tag @s add cl_dead
execute as @p[scores={cl_damage=1..},distance=..50] at @s run function custom_loot:killer
function custom_loot:killed
kill @s
