#######
# Compiled from data/custom_loot/functions/death.mcscript
# to .//data/custom_loot/functions/killed.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute if entity @s[type=minecraft:bat] run function #custom_loot:killed/bat

execute if entity @s[type=minecraft:blaze] run function #custom_loot:killed/blaze

execute if entity @s[type=minecraft:cat] run function #custom_loot:killed/cat

execute if entity @s[type=minecraft:cave_spider] run function #custom_loot:killed/cave_spider

execute if entity @s[type=minecraft:chicken] run function #custom_loot:killed/chicken

execute if entity @s[type=minecraft:cod] run function #custom_loot:killed/cod

execute if entity @s[type=minecraft:cow] run function #custom_loot:killed/cow

execute if entity @s[type=minecraft:creeper] run function #custom_loot:killed/creeper

execute if entity @s[type=minecraft:dolphin] run function #custom_loot:killed/dolphin

execute if entity @s[type=minecraft:donkey] run function #custom_loot:killed/donkey

execute if entity @s[type=minecraft:drowned] run function #custom_loot:killed/drowned

execute if entity @s[type=minecraft:elder_guardian] run function #custom_loot:killed/elder_guardian

execute if entity @s[type=minecraft:enderman] run function #custom_loot:killed/enderman

execute if entity @s[type=minecraft:endermite] run function #custom_loot:killed/endermite

execute if entity @s[type=minecraft:evoker] run function #custom_loot:killed/evoker

execute if entity @s[type=minecraft:fox] run function #custom_loot:killed/fox

execute if entity @s[type=minecraft:ghast] run function #custom_loot:killed/ghast

execute if entity @s[type=minecraft:giant] run function #custom_loot:killed/giant

execute if entity @s[type=minecraft:guardian] run function #custom_loot:killed/guardian

execute if entity @s[type=minecraft:horse] run function #custom_loot:killed/horse

execute if entity @s[type=minecraft:husk] run function #custom_loot:killed/husk

execute if entity @s[type=minecraft:illusioner] run function #custom_loot:killed/illusioner

execute if entity @s[type=minecraft:iron_golem] run function #custom_loot:killed/iron_golem

execute if entity @s[type=minecraft:llama] run function #custom_loot:killed/llama

execute if entity @s[type=minecraft:magma_cube] run function #custom_loot:killed/magma_cube

execute if entity @s[type=minecraft:mooshroom] run function #custom_loot:killed/mooshroom

execute if entity @s[type=minecraft:mule] run function #custom_loot:killed/mule

execute if entity @s[type=minecraft:ocelot] run function #custom_loot:killed/ocelot

execute if entity @s[type=minecraft:panda] run function #custom_loot:killed/panda

execute if entity @s[type=minecraft:parrot] run function #custom_loot:killed/parrot

execute if entity @s[type=minecraft:phantom] run function #custom_loot:killed/phantom

execute if entity @s[type=minecraft:pig] run function #custom_loot:killed/pig

execute if entity @s[type=minecraft:pillager] run function #custom_loot:killed/pillager

execute if entity @s[type=minecraft:polar_bear] run function #custom_loot:killed/polar_bear

execute if entity @s[type=minecraft:pufferfish] run function #custom_loot:killed/pufferfish

execute if entity @s[type=minecraft:rabbit] run function #custom_loot:killed/rabbit

execute if entity @s[type=minecraft:ravager] run function #custom_loot:killed/ravager

execute if entity @s[type=minecraft:salmon] run function #custom_loot:killed/salmon

execute if entity @s[type=minecraft:shulker] run function #custom_loot:killed/shulker

execute if entity @s[type=minecraft:silverfish] run function #custom_loot:killed/silverfish

execute if entity @s[type=minecraft:skeleton] run function #custom_loot:killed/skeleton

execute if entity @s[type=minecraft:skeleton_horse] run function #custom_loot:killed/skeleton_horse

execute if entity @s[type=minecraft:slime] run function #custom_loot:killed/slime

execute if entity @s[type=minecraft:snow_golem] run function #custom_loot:killed/snow_golem

execute if entity @s[type=minecraft:spider] run function #custom_loot:killed/spider

execute if entity @s[type=minecraft:squid] run function #custom_loot:killed/squid

execute if entity @s[type=minecraft:stray] run function #custom_loot:killed/stray

execute if entity @s[type=minecraft:trader_llama] run function #custom_loot:killed/trader_llama

execute if entity @s[type=minecraft:tropical_fish] run function #custom_loot:killed/tropical_fish

execute if entity @s[type=minecraft:turtle] run function #custom_loot:killed/turtle

execute if entity @s[type=minecraft:vex] run function #custom_loot:killed/vex

execute if entity @s[type=minecraft:villager] run function #custom_loot:killed/villager

execute if entity @s[type=minecraft:vindicator] run function #custom_loot:killed/vindicator

execute if entity @s[type=minecraft:wandering_trader] run function #custom_loot:killed/wandering_trader

execute if entity @s[type=minecraft:witch] run function #custom_loot:killed/witch

execute if entity @s[type=minecraft:wither_skeleton] run function #custom_loot:killed/wither_skeleton

execute if entity @s[type=minecraft:wolf] run function #custom_loot:killed/wolf

execute if entity @s[type=minecraft:zombie] run function #custom_loot:killed/zombie

execute if entity @s[type=minecraft:zombie_horse] run function #custom_loot:killed/zombie_horse

execute if entity @s[type=minecraft:zombie_pigman] run function #custom_loot:killed/zombie_pigman

execute if entity @s[type=minecraft:zombie_villager] run function #custom_loot:killed/zombie_villager

