#######
# Compiled from data/custom_loot/functions/death.mcscript
# to .//data/custom_loot/functions/killer.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:bat] run function #custom_loot:killer/bat

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:blaze] run function #custom_loot:killer/blaze

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:cat] run function #custom_loot:killer/cat

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:cave_spider] run function #custom_loot:killer/cave_spider

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:chicken] run function #custom_loot:killer/chicken

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:cod] run function #custom_loot:killer/cod

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:cow] run function #custom_loot:killer/cow

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:creeper] run function #custom_loot:killer/creeper

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:dolphin] run function #custom_loot:killer/dolphin

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:donkey] run function #custom_loot:killer/donkey

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:drowned] run function #custom_loot:killer/drowned

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:elder_guardian] run function #custom_loot:killer/elder_guardian

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:enderman] run function #custom_loot:killer/enderman

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:endermite] run function #custom_loot:killer/endermite

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:evoker] run function #custom_loot:killer/evoker

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:fox] run function #custom_loot:killer/fox

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:ghast] run function #custom_loot:killer/ghast

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:giant] run function #custom_loot:killer/giant

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:guardian] run function #custom_loot:killer/guardian

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:horse] run function #custom_loot:killer/horse

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:husk] run function #custom_loot:killer/husk

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:illusioner] run function #custom_loot:killer/illusioner

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:iron_golem] run function #custom_loot:killer/iron_golem

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:llama] run function #custom_loot:killer/llama

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:magma_cube] run function #custom_loot:killer/magma_cube

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:mooshroom] run function #custom_loot:killer/mooshroom

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:mule] run function #custom_loot:killer/mule

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:ocelot] run function #custom_loot:killer/ocelot

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:panda] run function #custom_loot:killer/panda

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:parrot] run function #custom_loot:killer/parrot

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:phantom] run function #custom_loot:killer/phantom

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:pig] run function #custom_loot:killer/pig

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:pillager] run function #custom_loot:killer/pillager

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:polar_bear] run function #custom_loot:killer/polar_bear

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:pufferfish] run function #custom_loot:killer/pufferfish

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:rabbit] run function #custom_loot:killer/rabbit

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:ravager] run function #custom_loot:killer/ravager

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:salmon] run function #custom_loot:killer/salmon

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:shulker] run function #custom_loot:killer/shulker

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:silverfish] run function #custom_loot:killer/silverfish

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:skeleton] run function #custom_loot:killer/skeleton

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:skeleton_horse] run function #custom_loot:killer/skeleton_horse

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:slime] run function #custom_loot:killer/slime

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:snow_golem] run function #custom_loot:killer/snow_golem

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:spider] run function #custom_loot:killer/spider

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:squid] run function #custom_loot:killer/squid

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:stray] run function #custom_loot:killer/stray

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:trader_llama] run function #custom_loot:killer/trader_llama

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:tropical_fish] run function #custom_loot:killer/tropical_fish

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:turtle] run function #custom_loot:killer/turtle

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:vex] run function #custom_loot:killer/vex

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:villager] run function #custom_loot:killer/villager

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:vindicator] run function #custom_loot:killer/vindicator

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:wandering_trader] run function #custom_loot:killer/wandering_trader

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:witch] run function #custom_loot:killer/witch

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:wither_skeleton] run function #custom_loot:killer/wither_skeleton

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:wolf] run function #custom_loot:killer/wolf

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:zombie] run function #custom_loot:killer/zombie

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:zombie_horse] run function #custom_loot:killer/zombie_horse

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:zombie_pigman] run function #custom_loot:killer/zombie_pigman

execute if entity @e[limit=1,sort=nearest,tag=cl_dead,type=minecraft:zombie_villager] run function #custom_loot:killer/zombie_villager
