#######
# Compiled from data/custom_loot/functions/management.mcscript
# to .//data/custom_loot/functions/uninstall.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives remove cl_temp
scoreboard objectives remove cl_health
scoreboard objectives remove cl_req_health
scoreboard objectives remove cl_damage
scoreboard objectives remove cl_killed_wither
scoreboard objectives remove cl_killed_ed